# Makefile
.EXPORT_ALL_VARIABLES:

GO111MODULE=on
GOPROXY=https://proxy.golang.org,direct
GOSUMDB=sum.golang.org
GOPRIVATE=github.com/cssbruno/gocep

.PHONY: update test ci install-quality-tools

update:
	@echo "########## Updating dependencies and checks ..."
	go get -u -t ./...
	go mod tidy
	go test ./...
	go test -race ./...
	go vet ./...
	@echo "dependency update completed"

test: 
	go test -v ./...
	go test -race -v ./...
	go vet ./...
	go test -v -covermode=atomic -coverprofile=coverage.out ./...
	go tool cover -func=coverage.out

install-quality-tools:
	go install honnef.co/go/tools/cmd/staticcheck@v0.6.1
	go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
	go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8

ci:
	go test ./...
	go test -race ./...
	go vet ./...
	$$(go env GOPATH)/bin/staticcheck ./...
	$$(go env GOPATH)/bin/golangci-lint run --timeout=5m --disable-all --enable=govet --enable=staticcheck ./...
	$$(go env GOPATH)/bin/govulncheck ./...
	go test ./examples/...
