# Makefile
.EXPORT_ALL_VARIABLES:

GO111MODULE=on
GOPROXY=https://proxy.golang.org,direct
GOSUMDB=sum.golang.org
GOPRIVATE=github.com/cssbruno/gocep

.PHONY: update test

update:
	@echo "########## Updating dependencies and checks ..."
	go get -u -t ./...
	go mod tidy
	go test ./...
	go test -race ./...
	go vet ./...
	@echo "dependency update completed"

test: 
	go test -v ./...
	go test -race -v ./...
	go vet ./...
	go test -v -covermode=atomic -coverprofile=coverage.out ./...
	go tool cover -func=coverage.out
